# Be sure to restart your server when you modify this file.
# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 50559223d3ca3c5fc0d5387c9cbc1943f12b6690c77edd60e57177695fa89b188031a40a868e29d99b810290837204edb4138125c5f71dd7c61af743a41d5570

test:
  secret_key_base: f451bd9dbac63b7b5bf60d1ce2fc7b3ba6e2f5ef194fd10a4cc8325794d8c1f1eb67c7ccb7ee1bd164e6b2b2f3241e09cc4ac982c62c25c7c86cd5e324969422

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: aebd9b334b3910bc237afa4c116e125f44e4d219152b9e3fa9a91cddbd6ac8e08395ba102508d9b2290ada460157abf554b29edd391c59734a8ddc8b9f5ab1f7